server:
  port: 8081
spring:
  application:
    name: mall-product-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    url: jdbc:mysql://localhost:3306/mall?serverTimezone=UTC
    username: root
    #    password: lyh
#    password: abc@135790
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  type-aliases-package: edu.fdzc.mallproduct.entity
  configuration:
    map-underscore-to-camel-case: true